name: Chunker_Tweaked
version: 1.21.7
main: xyz.acyber.chunker_Tweaked.Chunker_Tweaked
author: Go0fy_Go0ber, AidThePorter
description: Fast and Efficient Async Minecraft World Pre-generator
api-version: 1.21.7
folia-supported: true
paperweight-mappings-namespace: mojang
commands:
  pregen:
    description: "Enable chunk pre-generation, or reset pregen state. Usage: /pregen <ParallelTasksMultiplier> <PrintUpdateDelay> <world> <RadiusInBlocks/Chunks/Regions> OR /pregen reset <world>"
    permission: chunker.pregen
    usage: |
      /pregen <ParallelTasksMultiplier> <PrintUpdateDelayin(Seconds/Minutes/Hours)> <world> <Radiusin(Blocks/Chunks/Regions) or default>
      /pregen reset <world>
  pregenoff:
    description: Disable pre-generation
    permission: chunker.pregenoff
    usage: /pregenoff [world]
permissions:
  chunker.pregen:
    description: Grants permission to use the pre-generation command with customizable parameters
    default: op
  chunker.pregenoff:
    description: Grants permission to disable pre-generation using the /pregenoff command
    default: op
  chunker.reset:
    description: Grants permission to use /pregen reset to delete pregeneration data for a world
    default: op
  chunker.*:
    description: Provides access to all Chunker commands
    default: op
    children:
      chunker.pregen: true
      chunker.pregenoff: true
      chunker.reset: true